site_name: Red Hat Satellite Compliance
docs_dir: publishing-house/spec
nav:
- Home: index.md
- Design Spec: design.md
- Modules:
  - Module 1 - Introduction: modules/module-01-introduction.md
  - Module 2 - Content View: modules/module-02-content-view.md
  - Module 3 - Activation Key: modules/module-03-activation-key.md
  - Module 4 - Openscap Content: modules/module-04-openscap-content.md
  - Module 5 - Host Group: modules/module-05-host-group.md
  - Module 6 - Compliance Policy: modules/module-06-compliance-policy.md
  - Module 7 - Register Hosts: modules/module-07-register-hosts.md
  - Module 8 - Install Client: modules/module-08-install-client.md
  - Module 9 - Run Scan: modules/module-09-run-scan.md
plugins:
- techdocs-core
